### ISSUE TITLE
does not work with cachix install nix action

### ISSUE THREAD

**Issue by itslychee** [wimpysworld/nothing-but-nix#24]
```yml
  steps:
      - uses: actions/checkout@v4
      - name: QEMU static binaries
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install qemu-user-static
      - uses: wimpysworld/nothing-but-nix@main
        with:
          nix-permission-edict: true
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
            extra-platforms = aarch64-linux i686-linux
```

github action output:
```
...
  install: creating directory '/nix/var/nix/gcroots/per-user'
  install: creating directory '/nix/var/nix/profiles/per-user'
  install: creating directory '/nix/store'
  install: creating directory '/etc/nix'
  
  ~~> Installing Nix
  /nix/_temp/nix-binary-tarball-unpack.UYv2gEyjuM/unpack/nix-2.29.0-x86_64-linux/install-multi-user: line 835: cd: /nix/_temp/nix-binary-tarball-unpack.UYv2gEyjuM/unpack/nix-2.29.0-x86_64-linux: Permission denied
  rm: cannot remove '/nix/_temp/tmp.2EkUYIPFm0': Operation not permitted
  rm: cannot remove '/nix/_temp/nix-binary-tarball-unpack.UYv2gEyjuM': Operation not permitted
  rm: cannot remove '/nix/_temp/tmp.ZLfSTzspDD': Operation not permitted
  
```

[job](https://github.com/wires-org/wire/actions/runs/15419903667/job/43391967406)
